# Generated by Django 3.2.11 on 2022-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperationmindlog',
            name='log_event',
        ),
        migrations.AlterField(
            model_name='cooperationmindlog',
            name='operator',
            field=models.BigIntegerField(null=True, verbose_name='操作人'),
        ),
    ]
