# Generated by Django 3.2.11 on 2022-03-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_snapshot_log_id_cooperationmind_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationmind',
            name='data_format',
            field=models.CharField(default='node_array', max_length=32, verbose_name='数据格式化类型'),
            preserve_default=False,
        ),
    ]
